service:
  name: api-service
  runtime: nodejs18.x
  handler: index.handler
  memory: 512
  timeout: 60
  
  api:
    path: /api
    method: ANY
    public: true
    cors: true
      
  environment:
    STAGE: dev
      
  # Secrets
  secrets:
    - name: API_KEYS
      secretId: api-service/api-keys