ingress:
  name: api-ingress
  annotations:
    route53.hostedZoneId: Z00976892A2KHU6N0F7PT
    domain.existing: "true"  
  tls:
    - hosts:
        - sample.awscloudclubs.com
      certificateArn: arn:aws:acm:us-east-1:955228589631:certificate/f5043bf7-29c2-48f6-a6d4-68f2c5f36f93
  rules:
    - host: sample.awscloudclubs.com
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: hello-service
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: user-service
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: orders-service