ingress:
  name: my-ingress
  annotations:
    route53.hostedZoneId: ZXXXXXXXXXXXXXXXXX  # Optional: Route53 hosted zone ID
  tls:
    - hosts:
        - api.example.com
        - admin.example.com
      certificateArn: arn:aws:acm:region:account-id:certificate/certificate-id
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /users
            pathType: Prefix  # Prefix or Exact
            backend:
              service:
                name: user-service
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: product-service
    - host: admin.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-service